services:
  insadb:
    image: postgres:15
    container_name: central_${ENV}_postgres
    env_file: .env
    ports:
      - "${HOST_POSTGRES_PORT:-5432}:5432"
    volumes:
      - central_postgres_data:/var/lib/postgresql/data
    networks:
      - central_orc_net
    restart: always

  django_server:
    build: .
    container_name: central_${ENV}_django
    env_file: .env
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./static:/app/static
    ports:
      - "${HOST_DJANGO_PORT:-8000}:8000"
    depends_on:
      - insadb
    networks:
      - centeral_orc_net
    restart: always
  redis:
    image: redis:7
    container_name: central_redis
    command: ["redis-server", "--appendonly", "yes", "--save", "60", "1"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - centeral_orc_net
    restart: always
  celery_worker:
    build: .
    container_name: central_celery_worker
    env_file:
      - .env
    command: celery -A InsaBackednLatest worker -l info --concurrency=2 --max-tasks-per-child=50
    depends_on:
      - redis
      - insadb
      - django_server
    volumes:
      - .:/app
    networks:
      - centeral_orc_net
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M


volumes:
  dev_central_postgres_primary:
  redis_data:
networks:
  centeral_orc_net:
    external: true
