services:
  insadb:
    image: postgres:15
    container_name: central_postgres_primary
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - central_postgres_data:/var/lib/postgresql/data
    networks:
      - centeral_orc_net
    restart: always
  django_server:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8010:8000"
    depends_on:
      - insadb
    networks:
      - centeral_orc_net
    restart: always

volumes:
  central_postgres_data:
networks:
  centeral_orc_net:
    external: true
