services:
  insadb:
    image: postgres:15
    container_name: central_postgres_primary
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - central_postgres_data:/var/lib/postgresql/data
    networks:
      - centeral_orc_net
    restart: always
  django_server:
    build: .
    command: ./entrypoint.sh
    env_file:
      - .env
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - insadb
    networks:
      - centeral_orc_net
    restart: always

volumes:
  central_postgres_data:
networks:
  centeral_orc_net:
    external: true
